/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import negocio.ClienteCaixa;
import negocio.ClienteTerminal;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Scaketti
 */
public class TelaCConectados extends javax.swing.JFrame {

    ArrayList<ClienteTerminal> cTerminalConectados = null;
    ArrayList<ClienteCaixa> cCaixaConectados = null;
    /**
     * Creates new form TelaCConectados
     */
    public TelaCConectados(ArrayList<ClienteTerminal> cTerminalConectados, ArrayList<ClienteCaixa> cCaixaConectados) {
        initComponents();
        
        this.cTerminalConectados = cTerminalConectados;
        this.cCaixaConectados = cCaixaConectados;
        getClientes();
    }
    
    public void getClientes() {
        try {
            DefaultTableModel modeloTable = (DefaultTableModel) getTblClientes().getModel();

            while (modeloTable.getRowCount() > 0) {
                modeloTable.removeRow(0);
            }

            for (ClienteTerminal c : cTerminalConectados) {
               modeloTable.addRow(new Object[]{c.getNome(), "Cliente Mesa: " + c.getNumTerminal()});
            }
            
            for (ClienteCaixa c : cCaixaConectados) {
               modeloTable.addRow(new Object[]{c.getNome(), "Funcionário"});
            }

        } catch (Exception e) {
            System.out.println("Erro: Mensagem: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlClientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpnlClientes.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes Conectados"));

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(tblClientes);

        javax.swing.GroupLayout jpnlClientesLayout = new javax.swing.GroupLayout(jpnlClientes);
        jpnlClientes.setLayout(jpnlClientesLayout);
        jpnlClientesLayout.setHorizontalGroup(
            jpnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnlClientesLayout.setVerticalGroup(
            jpnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnlClientes;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the tblClientes
     */
    public javax.swing.JTable getTblClientes() {
        return tblClientes;
    }

    /**
     * @param tblClientes the tblClientes to set
     */
    public void setTblClientes(javax.swing.JTable tblClientes) {
        this.tblClientes = tblClientes;
    }
}
