/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.rmi.Naming;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.ClienteCaixa;
import negocio.Produto;
import negocio.ServidorBarInterface;

/**
 *
 * @author foxdie
 */
public class TelaInsertAlterProdutos extends javax.swing.JFrame {
    TelaManterProdutos tManter;
    ClienteCaixa c;
    Produto pAlter = null;
    String nomeProdutoAntigo;

    /**
     * Creates new form TelaInsercaoProdutos
     */
    //Inserir
    public TelaInsertAlterProdutos(TelaManterProdutos tManter, ClienteCaixa c) {
        initComponents();
        this.tManter = tManter;
        this.c = c;
    }
    
    //Alterar
    public TelaInsertAlterProdutos(TelaManterProdutos tManter, ClienteCaixa c, Produto p) {
        initComponents();
        this.tManter = tManter;
        this.c = c;
        this.pAlter = p;

        txtIdProduto.setText(p.getIdProduto() + "");
        txtNomeProduto.setText(p.getNome());
        nomeProdutoAntigo = p.getNome();
        txtQtd.setText(p.getQtd() + "");
        txtPreco.setText(p.getPreco() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeProduto = new javax.swing.JLabel();
        lblQtd = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        txtNomeProduto = new javax.swing.JTextField();
        txtQtd = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblIdProduto = new javax.swing.JLabel();
        txtIdProduto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNomeProduto.setText("Nome do Produto:");

        lblQtd.setText("Quantidade:");

        lblPreco.setText("Preço do produto:");

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblIdProduto.setText("ID:");

        txtIdProduto.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNomeProduto)
                                    .addComponent(lblQtd)
                                    .addComponent(lblPreco))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIdProduto)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdProduto)
                    .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeProduto)
                    .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtd)
                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreco)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if (pAlter == null) {
            Produto p = new Produto();
            p.setNome(txtNomeProduto.getText());
            p.setPreco(Float.parseFloat(txtPreco.getText()));
            p.setQtd(Integer.parseInt(txtQtd.getText()));

            try { //Tenta se conectar com o servidor
                ServidorBarInterface servidor = (ServidorBarInterface) Naming.lookup("rmi://" + "127.0.0.1" + ":" + "1099" + "/bar");

                System.out.println(p);
                int validacao = servidor.insereProduto(p, c.getNome());

                if (validacao == 0) {
                    JOptionPane.showMessageDialog(null, "Produto inserido com sucesso!");
                    getProdutos();

                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Não foi possível inserir o produto, tente novamente!");
                    
                    this.dispose();
                }

            } catch (Exception e) {
                System.out.println("Erro: Mensagem: " + e.getMessage());
            }
        }else{
            pAlter.setNome(txtNomeProduto.getText());
            pAlter.setPreco(Float.parseFloat(txtPreco.getText()));
            pAlter.setQtd(Integer.parseInt(txtQtd.getText()));
            
            try { //Tenta se conectar com o servidor
                ServidorBarInterface servidor = (ServidorBarInterface) Naming.lookup("rmi://" + "127.0.0.1" + ":" + "1099" + "/bar");

                int validacao = servidor.alteraProduto(pAlter, c.getNome());

                if (validacao == 0) {
                    JOptionPane.showMessageDialog(null, "Produto alterado com sucesso!");
                    getProdutos();

                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Não foi possível alterar o produto, tente novamente!");
                    
                    this.dispose();
                }

            } catch (Exception e) {
                System.out.println("Erro: Mensagem: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    public void getProdutos() {
        try {
            ServidorBarInterface servidor = (ServidorBarInterface) Naming.lookup("rmi://" + "127.0.0.1" + ":" + "1099" + "/bar");
            ArrayList<Produto> pBusca = servidor.pesquisaProduto(c.getNome());

            DefaultTableModel modeloTable = (DefaultTableModel) tManter.getTblProdutos().getModel();

            while (modeloTable.getRowCount() > 0) {
                modeloTable.removeRow(0);
            }

            for (Produto p : pBusca) {
                modeloTable.addRow(new Object[]{p.getIdProduto(), p.getNome(), p.getQtd(), p.getPreco()});
            }

        } catch (Exception e) {
            System.out.println("Erro: Mensagem: " + e.getMessage());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel lblIdProduto;
    private javax.swing.JLabel lblNomeProduto;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblQtd;
    private javax.swing.JTextField txtIdProduto;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQtd;
    // End of variables declaration//GEN-END:variables
}
